name: documents_saver_app
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+2

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  go_router: ^6.5.5
  get_it: ^7.2.0
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  nanoid: ^1.0.0
  isar: ^3.0.5
  isar_flutter_libs: ^3.0.5
  path_provider: ^2.0.14
  flutter_slidable: ^2.0.0
  flutter_download_manager: ^0.5.5
  flutter_pdfview: ^1.3.0
  slang: ^3.16.0
  slang_flutter: ^3.16.0
  shared_preferences: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  isar_generator: ^3.0.5
  build_runner: ^2.3.3
  flutter_launcher_icons: ^0.13.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 22 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
  assets:
    - assets/i18n/
