name: documents_saver_app
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  go_router: ^6.5.5
  get_it: ^7.2.0
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  nanoid: ^1.0.0
  isar: ^3.0.5
  isar_flutter_libs: ^3.0.5
  dio: ^5.1.1
  path_provider: ^2.0.14
  flutter_slidable: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  isar_generator: ^3.0.5
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
